package com.mrntlu.projectconsumer.adapters.viewholders

import androidx.recyclerview.widget.RecyclerView
import com.mrntlu.projectconsumer.databinding.CellPaginationExhaustBinding
class PaginationExhaustViewHolder(binding: CellPaginationExhaustBinding): RecyclerView.ViewHolder(binding.root)